config/routes.rb
Rails.application.routes.draw do

  get 'sellers/new'

  get 'customers/new'

  get 'login' => 'sessions#new'

  post 'login' => 'sessions#create'

  delete 'logout' => 'sessions#destroy'

  get 'signup' => 'registered_users#new'

  root  'home#index'
  
  get 'product/index/:id' => 'product#index', as: 'product'

  get 'shop/index' => 'shop#index', as: 'shop'

  get 'checkout/index' => 'checkout#index', as: 'checkout'

  get 'cart/index' => 'cart#index', as: 'cart'

  get 'home/index' => 'home#index', as: 'home'

  get 'registered_users/show/:id' => 'registered_users#show', as: 'user'

  get 'search' => 'search#index', as: 'search'

  get 'product/delete/:id' => 'product#delete', as: 'product_delete'
  get 'product/bid/:id' => 'product#bid', as: 'product_bid'

  resources :registered_users
  resources :customers
  resources :sellers

end

app/models/auction_process.rb
class AuctionProcess < ActiveRecord::Base

	belongs_to :bid_info
	belongs_to :registered_user
	
end

app/models/bid_info.rb
class BidInfo < ActiveRecord::Base

	belongs_to :item
	has_many :auction_processes

end

app/models/customer.rb
class Customer < ActiveRecord::Base
	validates :registered_user_id, presence: true, uniqueness: true
	belongs_to :registered_user
	has_many :auction_processes
	
end

app/models/customer_review.rb
class CustomerReview < ActiveRecord::Base

	belongs_to :order

end

app/models/e_category.rb
class ECategory < ActiveRecord::Base

	has_many :e_info

	has_many :sub_cats, class_name: "ECategory", foreign_key: "parent_cat_id"

	# foreign key parent_cat_id is implicit
	belongs_to :parent_cat, class_name: "ECategory"
	
end

app/models/e_info.rb
class EInfo < ActiveRecord::Base

	has_many :e_reviews, dependent: :destroy
	has_many :e_tags, dependent: :destroy
	has_many :items
	belongs_to :e_category
	belongs_to :seller

end

app/models/e_review.rb
class EReview < ActiveRecord::Base

	belongs_to :e_info

end

app/models/e_tag.rb
class ETag < ActiveRecord::Base

	belongs_to :e_info
	
end

app/models/item.rb
class Item < ActiveRecord::Base

	belongs_to :e_info
	has_one :order
	has_one :bid_info
	
end

app/models/order.rb
class Order < ActiveRecord::Base

	belongs_to :item
	belongs_to :registered_user
	has_many :customer_reviews

end

app/models/registered_user.rb
class RegisteredUser < ActiveRecord::Base

	validates :username, presence: true, uniqueness: true
	has_many :auction_processes
	has_many :sellers
	has_many :orders
	
end

app/models/seller.rb
class Seller < ActiveRecord::Base
	validates :registered_user_id, presence: true, uniqueness: true
	belongs_to :registered_user
	has_many :e_infos

end

app/helpers/auctions_helper.rb
module AuctionsHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/product_helper.rb
module ProductHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/sellers_helper.rb
module SellersHelper
end

app/helpers/shop_helper.rb
module ShopHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>HelloWorld</title>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

	<!-- Google Fonts -->
	<link href='http://fonts.googleapis.com/css?family=Titillium+Web:400,200,300,700,600' rel='stylesheet' type='text/css'>
	<link href='http://fonts.googleapis.com/css?family=Roboto+Condensed:400,700,300' rel='stylesheet' type='text/css'>
	<link href='http://fonts.googleapis.com/css?family=Raleway:400,100' rel='stylesheet' type='text/css'>

	<!-- Custom CSS + JS -->
	<%= stylesheet_link_tag 'style', media: 'all', 'data-turbolinks-track' => true %>
	<%= stylesheet_link_tag 'responsive', media: 'all', 'data-turbolinks-track' => true %>
    
    <%= javascript_include_tag 'jquery.sticky', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'jquery.easing.1.3.min', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'main', 'data-turbolinks-track' => true %>

	<%= csrf_meta_tags %>

</head>
<body>

<%= render 'shared/nav' %>

<% flash.each do |message_type, message| %>
	<div class='container-fluid flash-border'>
		<br>
		<div class="alert alert-<%= message_type %>"><%= message %></div>
	</div>
<% end %>

<%= yield :body %>

<%= render 'shared/footer' %>

</body>
</html>

app/views/shared/_footer.html.erb
<div class="footer-top-area">
        <div class="zigzag-bottom"></div>
        <div class="container">
            <div class="row">
                <div class="col-md-3 col-sm-6">
                    <div class="footer-about-us">
                        <h2>e<span>Electronics</span></h2>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Perferendis sunt id doloribus vero quam laborum quas alias dolores blanditiis iusto consequatur, modi aliquid eveniet eligendi iure eaque ipsam iste, pariatur omnis sint! Suscipit, debitis, quisquam. Laborum commodi veritatis magni at?</p>
                        <div class="footer-social">
                            <a href="#" target="_blank"><i class="fa fa-facebook"></i></a>
                            <a href="#" target="_blank"><i class="fa fa-twitter"></i></a>
                            <a href="#" target="_blank"><i class="fa fa-youtube"></i></a>
                            <a href="#" target="_blank"><i class="fa fa-linkedin"></i></a>
                            <a href="#" target="_blank"><i class="fa fa-pinterest"></i></a>
                        </div>
                    </div>
                </div>
                
                <div class="col-md-3 col-sm-6">
                    <div class="footer-menu">
                        <h2 class="footer-wid-title">User Navigation </h2>
                        <ul>
                            <li><a href="#">My account</a></li>
                            <li><a href="#">Order history</a></li>
                            <li><a href="#">Wishlist</a></li>
                            <li><a href="#">Vendor contact</a></li>
                            <li><%= link_to 'Front page', root_url, 'data-no-turbolink'.to_sym => true %></li>
                        </ul>                        
                    </div>
                </div>
                
                <div class="col-md-3 col-sm-6">
                    <div class="footer-menu">
                        <h2 class="footer-wid-title">Site Navigation</h2>
                        <ul>
                            <li><%= link_to 'Browse', shop_url, 'data-no-turbolink'.to_sym => true %></li>
                            <li><%= link_to 'Product', product_url(:id => 1), 'data-no-turbolink'.to_sym => true %></li>
                            <li><%= link_to 'Cart', cart_url, 'data-no-turbolink'.to_sym => true %></li>
                            <li><%= link_to 'Checkout', checkout_url, 'data-no-turbolink'.to_sym => true %></li>
                        </ul>                        
                    </div>
                </div>
                
                <div class="col-md-3 col-sm-6">
                    <div class="footer-newsletter">
                        <h2 class="footer-wid-title">Newsletter</h2>
                        <p>Sign up to our newsletter and get exclusive deals you wont find anywhere else straight to your inbox!</p>
                        <div class="newsletter-form">
                            <form action="#">
                                <input type="email" placeholder="Type your email">
                                <input type="submit" value="Subscribe">
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div> <!-- End footer top area -->
    
    <div class="footer-bottom-area">
        <div class="container">
            <div class="row">
                <div class="col-md-8">
                </div>
                
                <div class="col-md-4">
                    <div class="footer-card-icon">
                        <i class="fa fa-cc-discover"></i>
                        <i class="fa fa-cc-mastercard"></i>
                        <i class="fa fa-cc-paypal"></i>
                        <i class="fa fa-cc-visa"></i>
                    </div>
                </div>
            </div>
        </div>
    </div> <!-- End footer bottom area -->

app/views/shared/_nav.html.erb
    <div class="header-area">
        <div class="container">
            <div class="row">
                <div class="col-md-8">
                    <div class="user-menu">
                        <ul>
                            <% if logged_in? %>
                            <i class="fa fa-user"></i><li><a href = "/registered_users/<%= @current_user.id%>">My account</a></li>
                            <li><a href="#"><i class="fa fa-heart"></i> Wishlist</a></li>
                            <li><%= link_to 'Orders', cart_url, 'data-no-turbolink'.to_sym => true %></li>
                            <li><%= link_to 'Checkout', checkout_url, 'data-no-turbolink'.to_sym => true %></li>
                            <li><%= link_to 'Logout', logout_path, method: "delete" %></li>
                            <% else %>
                            <i class="fa fa-user"></i><li><%= link_to 'Login', login_url, 'data-no-turbolink'.to_sym => true %></li>
                            <li><%= link_to 'Signup', signup_url %></li>
                            <% end %>
                        </ul>
                    </div>
                </div>
                
                <div class="col-md-4">
                    <div class="header-right">
                        <ul class="list-unstyled list-inline">
                            <li class="dropdown dropdown-small">
                                <a data-toggle="dropdown" data-hover="dropdown" class="dropdown-toggle" href="#"><span class="key">currency :</span><span class="value">USD </span><b class="caret"></b></a>
                                <ul class="dropdown-menu">
                                    <li><a href="#">USD</a></li>
                                    <li><a href="#">INR</a></li>
                                    <li><a href="#">GBP</a></li>
                                </ul>
                            </li>

                            <li class="dropdown dropdown-small">
                                <a data-toggle="dropdown" data-hover="dropdown" class="dropdown-toggle" href="#"><span class="key">language :</span><span class="value">English </span><b class="caret"></b></a>
                                <ul class="dropdown-menu">
                                    <li><a href="#">English</a></li>
                                    <li><a href="#">French</a></li>
                                    <li><a href="#">German</a></li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div> <!-- End header area -->
    
    <div class="site-branding-area">
        <div class="container">
            <div class="row">
                <div class="col-sm-6">
                    <div class="logo">
                        <h1><span><%= link_to 'HelloWorld', root_url, 'data-no-turbolink'.to_sym => true %></span></h1>
                    </div>
                </div>
                
                <!-- <div class="col-sm-6">
                    <div class="shopping-item">
                        <a href="cart/index">Cart - <span class="cart-amunt">$800</span> <i class="fa fa-shopping-cart"></i> <span class="product-count">5</span></a>
                    </div>
                </div> -->
            </div>
        </div>
    </div> <!-- End site branding area -->
    
    <div class="mainmenu-area">
        <div class="container">
            <div class="row">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div> 
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav" id="main-menu">
                        <li class="<%= 'active' if current_page?(root_url) %>"><%= link_to 'Home', root_url, 'data-no-turbolink'.to_sym => true %></li>
                        <li class="<%= 'active' if current_page?(shop_url) %>"><%= link_to 'Browse', shop_url, 'data-no-turbolink'.to_sym => true %></li>
                        <li class="<%= 'active' if request.original_url =~ /#{Regexp.quote('/product/index/')}\d/ %> %>"><%= link_to 'Product', product_url(:id => 1), 'data-no-turbolink'.to_sym => true %></li>
                        <li class="<%= 'active' if current_page?(cart_url) %>"><%= link_to 'Orders', cart_url, 'data-no-turbolink'.to_sym => true %></li>
                        <li class="<%= 'active' if current_page?(checkout_url) %>"><%= link_to 'Checkout', checkout_url, 'data-no-turbolink'.to_sym => true %></li>
                    </ul>

                    <div class="col-sm-3 col-md-3 pull-right">
                        <%= form_tag search_path, method: 'get',:class => 'navbar-form' do %>
                            <div class="input-group">
                                <%= text_field_tag :search, params[:search] %>
                                <div class="input-group-btn">
                                    <%= submit_tag "Search", :class => 'btn btn-default' %>
                                </div>
                            </div>
                        <% end %>

                        <!-- <form class="navbar-form" role="search">
                            <div class="input-group">
                                <input type="text" class="form-control" placeholder="Search" name="srch-term" id="srch-term">
                                <div class="input-group-btn">
                                    <button class="btn btn-default" type="submit">Submit</button>
                                </div>
                            </div>
                        </form> -->
                    </div>
                </div>
            </div>
        </div>
    </div> <!-- End mainmenu area -->