config/routes.rb
Rails.application.routes.draw do

  get 'sellers/new'

  get 'customers/new'

  get 'login' => 'sessions#new'

  post 'login' => 'sessions#create'

  delete 'logout' => 'sessions#destroy'

  get 'signup' => 'registered_users#new'

  root  'home#index'
  
  get 'product/index/:id' => 'product#index', as: 'product'

  get 'shop/index' => 'shop#index', as: 'shop'

  get 'checkout/index' => 'checkout#index', as: 'checkout'

  get 'cart/index' => 'cart#index', as: 'cart'

  get 'home/index' => 'home#index', as: 'home'

  get 'registered_users/show/:id' => 'registered_users#show', as: 'user'

  get 'search' => 'search#index', as: 'search'

  get 'product/delete/:id' => 'product#delete', as: 'product_delete'
  get 'product/bid/:id' => 'product#bid', as: 'product_bid'

  resources :registered_users
  resources :customers
  resources :sellers

end

app/models/auction_process.rb
class AuctionProcess < ActiveRecord::Base

	belongs_to :bid_info
	belongs_to :registered_user
	
end

app/models/bid_info.rb
class BidInfo < ActiveRecord::Base

	belongs_to :item
	has_many :auction_processes

end

app/models/customer.rb
class Customer < ActiveRecord::Base
	validates :registered_user_id, presence: true, uniqueness: true
	belongs_to :registered_user
	has_many :auction_processes
	
end

app/models/customer_review.rb
class CustomerReview < ActiveRecord::Base

	belongs_to :order

end

app/models/e_category.rb
class ECategory < ActiveRecord::Base

	has_many :e_info

	has_many :sub_cats, class_name: "ECategory", foreign_key: "parent_cat_id"

	# foreign key parent_cat_id is implicit
	belongs_to :parent_cat, class_name: "ECategory"
	
end

app/models/e_info.rb
class EInfo < ActiveRecord::Base

	has_many :e_reviews, dependent: :destroy
	has_many :e_tags, dependent: :destroy
	has_many :items
	belongs_to :e_category
	belongs_to :seller

end

app/models/e_review.rb
class EReview < ActiveRecord::Base

	belongs_to :e_info

end

app/models/e_tag.rb
class ETag < ActiveRecord::Base

	belongs_to :e_info
	
end

app/models/item.rb
class Item < ActiveRecord::Base

	belongs_to :e_info
	has_one :order
	has_one :bid_info
	
end

app/models/order.rb
class Order < ActiveRecord::Base

	belongs_to :item
	belongs_to :registered_user
	has_many :customer_reviews

end

app/models/registered_user.rb
class RegisteredUser < ActiveRecord::Base

	validates :username, presence: true, uniqueness: true
	has_many :auction_processes
	has_many :sellers
	has_many :orders
	
end

app/models/seller.rb
class Seller < ActiveRecord::Base
	validates :registered_user_id, presence: true, uniqueness: true
	belongs_to :registered_user
	has_many :e_infos

end

app/controllers/product_controller.rb
class ProductController < ApplicationController

  include SessionsHelper

  def index

  	@einfo = EInfo.where(:id => params[:id]).limit(1)
  	@einfo.each { |ei|
  		@einfo = ei
  	}

  	@cat_array = Array.new
  	make_cat_array(@einfo.e_category_id)

    @product_array = Array.new
    length = EInfo.all().length

    (16).times do
      push_rand(length)
    end

  end

  def delete
    if !logged_in?
      flash.now[:danger] = 'Not logged in!'

      redirect_to product_url(:id => params[:id])
      return
    end
    
    customer = Seller.where(registered_user_id: current_user.id)
    customer.each { |ea|
      customer = ea
    }

    if !customer.blank?
      params[:quantity].to_i.times do |i|
        Order.create(:bank => customer.bank_account, credit: '999xxxxxxxxxxxxx', address: customer.address, item_id: params[:id], registered_user_id: current_user.id)
      end
    else
      flash.now[:danger] = 'You have not created buyer info for your account yet. Visit the My Account page to do so.'
      return
    end

    item = Item.where(:e_info_id => params[:id]).limit(1)
    item.each { |ei|
      item = ei
    }

    if (item.quantity.to_i - params[:quantity].to_i) > 1
      item.update(:e_info_id => params[:id], :quantity => (item.quantity.to_i - params[:quantity].to_i).to_s)
    else
      item.update(:e_info_id => params[:id], :quantity => 0.to_s)
      redirect_to cart_url
      return
    end

    redirect_to cart_url
    return
  end

  def bid
    if !logged_in?
      flash.now[:danger] = 'Not logged in!'

      redirect_to product_url(:id => params[:id])
      return
    end

    bi = BidInfo.where(:item_id => params[:hid]).limit(1)
    bi.each { |yy|
      bi = yy
    }

    ai = AuctionProcess.where(:bid_info_id => bi.id).order('bid_price DESC').limit(1)
    ai.each { |xx|
      ai = xx
    }

    if params[:bid].to_i > ai.bid_price.to_i
      ai.update(bid_price: params[:bid], bid_info_id: bi.id)
      AuctionProcess.create(bid_price: params[:bid].to_s, bid_info_id: bi.id, registered_user_id: current_user.id)
    else
      flash[:danger] = 'Bid is not greater than current going price!'
    end

    redirect_to cart_url
    return
  end

  def make_cat_array(cat1)
  	ECategory.where(:id => cat1).limit(1).each do |cat|
  		if cat.parent_cat_id != 0
  			@cat_array.push(cat.name)
  			make_cat_array(cat.parent_cat_id)
  		else
  			break
  		end
  	end
  end

  def push_rand(length)
    num = 1 + rand(length)

    if (@product_array.include?(num))
      push_rand(length)
    else
      @product_array.push(num)
    end

  end

end

app/helpers/auctions_helper.rb
module AuctionsHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/product_helper.rb
module ProductHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/sellers_helper.rb
module SellersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def log_in(user)
		session[:user_id] = user.id
	end

	def current_user
  		@current_user ||= RegisteredUser.find_by(id: session[:user_id])
	end

	def logged_in?
		!current_user.nil?
	end
  
	def log_out
		session.delete(:user_id)
		@current_user = nil
	end
end

app/helpers/shop_helper.rb
module ShopHelper
end

app/views/product/delete.html.erb
etetetett

app/views/product/index.html.erb
<%= content_for :body  do %>
    
    <div class="product-big-title-area">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="product-bit-title text-center">
                        <h2>Product</h2>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
    <div class="single-product-area">
        <div class="zigzag-bottom"></div>
        <div class="container">
            <div class="row">
                <div class="col-md-4">                 
                    <div class="single-sidebar">
                        <h2 class="sidebar-title">Other Products</h2>
                        <% @product_array.first(8).each do |product| %>
                            <% EInfo.where(id: product).each do |ei| %>
                                <div class="thubmnail-recent">
                                    <img src="img/product-thumb-1.jpg" class="recent-thumb" alt="">
                                    <h2><%= link_to ei.title, product_url(id: product), 'data-no-turbolink'.to_sym => true %></h2>                             
                                </div>
                            <% end %>
                        <% end %>
                    </div>
                </div>
                
                <div class="col-md-8">
                    <div class="product-content-right">
                        <div class="product-breadcroumb">
                            <a href="#">Home</a>
                            <% @cat_array.each do |cat| %>
                                <a href="#"><%= cat %></a>
                            <% end %>
                            <a href="#"><%= @einfo.title %></a>
                        </div>
                        
                        <div class="row">
                            <div class="col-sm-6">
                                <div class="product-images">
                                    <div class="product-main-img">
                                        <%= image_tag(@einfo.image_name, :alt => "") %>
                                    </div>
                                    
                                    <div class="product-gallery">
                                    </div>
                                </div>
                            </div>
                            
                            <div class="col-sm-6">
                                <div class="product-inner">
                                    <h2 class="product-name"><%= @einfo.title %></h2>
                                    <% Item.where(:e_info_id => @einfo.id).limit(1).each do |item| %>
                                        <% if item.auction != true %>
                                            <div class="product-inner-price">
                                                <ins>$<%= item.reserve_price %></ins> <del>$<%= (item.reserve_price.to_i + 10) %></del><br>
                                                <ins>Quanitity left:</ins> <%= item.quantity %>
                                            </div> 
                                        
                                            <% if current_user.nil? %>
                                                <div class="product-inner-price">
                                                    <ins>You are not logged in. You must log in to buy items.</ins>
                                                </div>
                                            <% else %>
                                                <% if item.quantity > 0 %>
                                                    <%= form_tag product_delete_path(params[:id]), method: 'get', :class => 'navbar-form' do %>
                                                            <div class="quanitiy">
                                                                <%= number_field_tag 'quantity', 1, :class => 'input-text qty text' %>
                                                            </div>
                                                            <br>
                                                            <%= submit_tag "Buy Item", :class => 'btn btn-default', data: { confirm: 'Are you sure you want to play this order?'} %>
                                                        </div>
                                                    <% end %>
                                                    <br>
                                                <% end %>
                                            <% end %>
                                        <% else %>
                                            <% BidInfo.where(:item_id => item.id).limit(1).each do |bid| %>
                                                <% AuctionProcess.where(:bid_info_id => bid.id).order('bid_price DESC').limit(1).each do |ap| %>
                                                    <div class="product-inner-price">
                                                        <ins>Auction Price</ins> $<%= ap.bid_price %><br>
                                                        <ins>Ending Date</ins> <%= bid.end_time.strftime("%m/%d/%y: %I:%M %p") %>
                                                    </div>


                                                    <% if current_user.nil? %>
                                                        <div class="product-inner-price">
                                                            <ins>You are not logged in. You must log in to place bids.</ins>
                                                        </div>
                                                    <% else %>
                                                        <% if Time.now.to_i < bid.end_time.to_i %>
                                                            <%= form_tag product_bid_path(params[:id]), method: 'get', :class => 'navbar-form' do %>
                                                                <div class='input-group'>
                                                                    <div class="quanitiy">
                                                                        $ <%= text_field_tag 'bid', 1, :class => 'input-text qty text' %>
                                                                    </div>
                                                                    <%= hidden_field_tag :hid, item.id %>
                                                                    <div class='input-group-btn'>
                                                                        <%= submit_tag "Place Bid", :class => 'btn btn-default', data: { confirm: 'Are you sure you want to play this bid?' } %>
                                                                    </div>
                                                                </div>
                                                            <% end %>
                                                            <br>
                                                        <% end %>
                                                    <% end %>

                                                <% end %>
                                            <% end %>
                                        <% end %>
                                    <% end %> 

         <!--                            <form action="" method='' class="cart">
                                        <div class="quantity">
                                            <input type="number" size="4" class="input-text qty text" title="Qty" value="1" name="quantity" min="1" step="1">
                                        </div>
                                        <button class="add_to_cart_button" type="submit">Buy item</button>
                                    </form>    -->
                                    
                                    <div class="product-inner-category">
                                        <p>Category: <a href=""><%= @cat_array.last %></a><br>
                                        Tags:
                                        <% ETag.where(:e_info_id => @einfo.id).each do |tag| %>
                                            <a href="#"><%= tag.name %></a>
                                            <% if ETag.where(:e_info_id => @einfo.id).last.name != tag.name %>
                                                ,
                                            <% else %>
                                                <% break %>
                                            <% end %>
                                        <% end %>
                                        </p>
                                    </div> 
                                    
                                    <div role="tabpanel">
                                        <ul class="product-tab" role="tablist">
                                            <li role="presentation" class="active"><a href="#home" aria-controls="home" role="tab" data-toggle="tab">Description</a></li>
                                            <li role="presentation"><a href="#profile" aria-controls="profile" role="tab" data-toggle="tab">Reviews</a></li>
                                        </ul>
                                        <div class="tab-content">
                                            <div role="tabpanel" class="tab-pane fade in active" id="home">
                                                <h2>Product Description</h2>  
                                                <p><%= @einfo.description %></p>
                                            </div>
                                            <div role="tabpanel" class="tab-pane fade" id="profile">
                                                <h2>Reviews</h2>

                                                <% EReview.where(:e_info_id => @einfo.id).each do |rev| %>
                                                    <div>
                                                        <% (rev.rating).times do %>
                                                            <i class="fa fa-star"></i>
                                                        <% end %><br>

                                                        <%= rev.comment %><br><br>
                                                    </div>
                                                <% end %>

                                            </div>
                                        </div>
                                    </div>
                                    
                                </div>
                            </div>
                        </div>
                        
                        
                        <div class="related-products-wrapper">
                            <h2 class="related-products-title">Related Products</h2>
                            <div class="related-products-carousel">

                                <% ECategory.where(:parent_cat_id => (ECategory.where(:id => @einfo.e_category_id).first.parent_cat_id)).each do |rel_item| %>
                                    <% EInfo.where(:e_category_id => rel_item.id).each do |rel_info| %>
                                    <div class="single-product">
                                        <div class="product-f-image">
                                            <%= image_tag(rel_info.image_name, :alt => "") %>
                                        </div>

                                        <h2><%= link_to rel_info.title, product_url(:id => rel_info.id), 'data-no-turbolink'.to_sym => true %></h2>

                                    </div>
                                    <% end %>
                                <% end %>
                                <!--
                                <div class="single-product">
                                    <div class="product-f-image">
                                        <img src="img/product-6.jpg" alt="">
                                        <div class="product-hover">
                                            <a href="" class="add-to-cart-link"><i class="fa fa-shopping-cart"></i> Add to cart</a>
                                            <a href="" class="view-details-link"><i class="fa fa-link"></i> See details</a>
                                        </div>
                                    </div>

                                    <h2><a href="">Samsung gallaxy note 4</a></h2>

                                    <div class="product-carousel-price">
                                        <ins>$400.00</ins>
                                    </div>                            
                                </div>-->
                            </div>
                        </div>
                    </div>                    
                </div>
            </div>
        </div>
    </div>

<% end %>